#ifndef _VEC_SORT_H_
#define _VEC_SORT_H_
#include <implementation/batcher-27-impl.h>
#include <implementation/batcher-5-impl.h>
#include <implementation/batcher-11-impl.h>
#include <implementation/batcher-13-impl.h>
#include <implementation/batcher-3-impl.h>
#include <implementation/batcher-18-impl.h>
#include <implementation/batcher-10-impl.h>
#include <implementation/batcher-20-impl.h>
#include <implementation/batcher-23-impl.h>
#include <implementation/batcher-12-impl.h>
#include <implementation/batcher-22-impl.h>
#include <implementation/batcher-21-impl.h>
#include <implementation/batcher-17-impl.h>
#include <implementation/batcher-2-impl.h>
#include <implementation/batcher-32-impl.h>
#include <implementation/batcher-30-impl.h>
#include <implementation/batcher-28-impl.h>
#include <implementation/batcher-26-impl.h>
#include <implementation/batcher-31-impl.h>
#include <implementation/batcher-29-impl.h>
#include <implementation/batcher-19-impl.h>
#include <implementation/batcher-15-impl.h>
#include <implementation/batcher-9-impl.h>
#include <implementation/batcher-14-impl.h>
#include <implementation/batcher-16-impl.h>
#include <implementation/batcher-25-impl.h>
#include <implementation/batcher-8-impl.h>
#include <implementation/batcher-4-impl.h>
#include <implementation/batcher-7-impl.h>
#include <implementation/batcher-6-impl.h>
#include <implementation/batcher-24-impl.h>
#endif
