#ifndef _VEC_SORT_H_
#define _VEC_SORT_H_
#include <implementation/bitonic-19-impl.h>
#include <implementation/bitonic-8-impl.h>
#include <implementation/bitonic-29-impl.h>
#include <implementation/bitonic-11-impl.h>
#include <implementation/bitonic-24-impl.h>
#include <implementation/bitonic-10-impl.h>
#include <implementation/bitonic-28-impl.h>
#include <implementation/bitonic-32-impl.h>
#include <implementation/bitonic-23-impl.h>
#include <implementation/bitonic-21-impl.h>
#include <implementation/bitonic-20-impl.h>
#include <implementation/bitonic-30-impl.h>
#include <implementation/bitonic-6-impl.h>
#include <implementation/bitonic-18-impl.h>
#include <implementation/bitonic-17-impl.h>
#include <implementation/bitonic-25-impl.h>
#include <implementation/bitonic-27-impl.h>
#include <implementation/bitonic-22-impl.h>
#include <implementation/bitonic-9-impl.h>
#include <implementation/bitonic-13-impl.h>
#include <implementation/bitonic-3-impl.h>
#include <implementation/bitonic-5-impl.h>
#include <implementation/bitonic-26-impl.h>
#include <implementation/bitonic-4-impl.h>
#include <implementation/bitonic-31-impl.h>
#include <implementation/bitonic-12-impl.h>
#include <implementation/bitonic-14-impl.h>
#include <implementation/bitonic-7-impl.h>
#include <implementation/bitonic-2-impl.h>
#include <implementation/bitonic-16-impl.h>
#include <implementation/bitonic-15-impl.h>
#endif
